version: "2.1"

services:
  memcached:
    container_name: ${CONTAINER_PREFIX}.memcached
    image: memcached:1.4.24
    # ports:
    #   - "11211:11211"

  elasticsearch:
    container_name: ${CONTAINER_PREFIX}.elasticsearch
    image: karacic/elasticsearch:${CONTAINER_PREFIX}-ginkgo.master
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_data:/usr/share/elasticsearch/logs

  mongo:
    # We use WiredTiger in all environments. In development environments we use small files
    # to conserve disk space, and disable the journal for a minor performance gain.
    # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    container_name: ${CONTAINER_PREFIX}.mongo
    image: mongo:3.2.16
    # ports:
    #  - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: ${CONTAINER_PREFIX}.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.6
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  lms:
    command: bash -c 'source /edx/app/edxapp/edxapp_env && while true; do python /edx/app/edxapp/edx-platform/manage.py lms runserver 0.0.0.0:18000 --settings devstack_docker; sleep 2; done'
    container_name: ${CONTAINER_PREFIX}.lms
    depends_on:
      - mysql
      - memcached
      - mongo
    # Allows attachment to the LMS service using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    environment:
      BOK_CHOY_HOSTNAME: ${CONTAINER_PREFIX}.lms
      BOK_CHOY_LMS_PORT: 18003
      BOK_CHOY_CMS_PORT: 18031
      EDXAPP_TEST_MONGO_HOST: ${CONTAINER_PREFIX}.mongo
      NO_PYTHON_UNINSTALL: 1
    image: karacic/edxapp:${CONTAINER_PREFIX}-ginkgo.master
    ports:
      - "18000:18000"
      - "19876:19876" # JS test debugging
      # - "18003:18003"
      # - "18031:18031"
    volumes:
      - edxapp_lms_assets:/edx/var/edxapp/staticfiles/

  studio:
    command: bash -c 'source /edx/app/edxapp/edxapp_env && while true; do python /edx/app/edxapp/edx-platform/manage.py cms runserver 0.0.0.0:18010 --settings devstack_docker; sleep 2; done'
    container_name: ${CONTAINER_PREFIX}.studio
    depends_on:
      - mysql
      - memcached
      - mongo
    # Allows attachment to the Studio service using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    environment:
      BOK_CHOY_HOSTNAME: ${CONTAINER_PREFIX}.studio
      BOK_CHOY_LMS_PORT: 18103
      BOK_CHOY_CMS_PORT: 18131
      EDXAPP_TEST_MONGO_HOST: ${CONTAINER_PREFIX}.mongo
      NO_PYTHON_UNINSTALL: 1
    image: karacic/edxapp:${CONTAINER_PREFIX}-ginkgo.master
    ports:
      - "18010:18010"
      - "19877:19877" # JS test debugging
      # - "18103:18103"
      # - "18131:18131"
    volumes:
      - edxapp_studio_assets:/edx/var/edxapp/staticfiles/

  forum:
    command: bash -c 'source /edx/app/forum/ruby_env && source /edx/app/forum/forum_env && cd /edx/app/forum/cs_comments_service && bundle install && while true; do ruby app.rb -o 0.0.0.0 ; sleep 2; done'
    container_name: ${CONTAINER_PREFIX}.forum
    depends_on:
      - mongo
      - memcached
      - elasticsearch
    image: karacic/forum:${CONTAINER_PREFIX}-ginkgo.master
    ports:
      - "18080:4567"


volumes:
  edxapp_lms_assets:
  edxapp_studio_assets:
  mongo_data:
  mysql_data:
  elasticsearch_data:
